** Student Grade Analyzer**





In [ ]:
#a NumPy array of 50 randomly generated scores (0–100)
import numpy as np

scores=np.random.randint(0,101,50)
scores


array([24, 23, 50, 16, 78, 77, 11,  1, 26,  8, 18, 92,  3, 41,  3, 70, 47,
       84, 40, 50, 54, 71, 98, 23, 64, 69,  7, 81, 61,  8, 57, 66, 55, 28,
        6, 95, 65,  0, 37, 37, 32, 83, 32, 13, 88, 19, 74, 15,  4, 44])

In [ ]:
mean=np.mean(scores)
mean


np.float64(42.96)

In [ ]:
median=np.median(scores)
median

np.float64(40.5)

In [ ]:
standard_deviation=np.std(scores)
standard_deviation

np.float64(29.275901352477604)

In [ ]:
percentile=np.percentile(scores, 50)
percentile

np.float64(40.5)

In [ ]:

maximum=np.max(scores)
print("Highest score is",maximum)
minimum=np.min(scores)
print("lowest score is:",minimum)

Highest score is 98
lowest score is: 0


In [ ]:
#Boolean masking
failed_students=scores<40
print("failed students are:",failed_students)
print(scores[failed_students])


failed students are: [ True  True False  True False False  True  True  True  True  True False
  True False  True False False False False False False False False  True
 False False  True False False  True False False False  True  True False
 False  True  True  True  True False  True  True False  True False  True
  True False]
[24 23 16 11  1 26  8 18  3  3 23  7  8 28  6  0 37 37 32 32 13 19 15  4]


In [ ]:
distiction=scores>85
print("Distinction scores :",distiction)
print(scores[distiction]) #Boolean indexing.
print("Number of students with distinction:",np.sum(distiction))

Distinction scores : [False False False False False False False False False False False  True
 False False False False False False False False False False  True False
 False False False False False False False False False False False  True
 False False False False False False False False  True False False False
 False False]
[92 98 95 88]
Number of students with distinction: 4


In [ ]:
#normalization
normalized_scores=(scores-minimum)/(maximum-minimum)
print("normalized scores :",normalized_scores)


normalized scores : [0.24489796 0.23469388 0.51020408 0.16326531 0.79591837 0.78571429
 0.1122449  0.01020408 0.26530612 0.08163265 0.18367347 0.93877551
 0.03061224 0.41836735 0.03061224 0.71428571 0.47959184 0.85714286
 0.40816327 0.51020408 0.55102041 0.7244898  1.         0.23469388
 0.65306122 0.70408163 0.07142857 0.82653061 0.62244898 0.08163265
 0.58163265 0.67346939 0.56122449 0.28571429 0.06122449 0.96938776
 0.66326531 0.         0.37755102 0.37755102 0.32653061 0.84693878
 0.32653061 0.13265306 0.89795918 0.19387755 0.75510204 0.15306122
 0.04081633 0.44897959]


In [ ]:
#reshape
scores_reshaped=scores.reshape(5,10)
print("reshaped scores :",scores_reshaped)

reshaped scores : [[24 23 50 16 78 77 11  1 26  8]
 [18 92  3 41  3 70 47 84 40 50]
 [54 71 98 23 64 69  7 81 61  8]
 [57 66 55 28  6 95 65  0 37 37]
 [32 83 32 13 88 19 74 15  4 44]]


In [ ]:
%cd ..

row wise average : [31.4 44.8 53.6 44.6 40.4]


**BONUS:- CALCULATE WEIGHTAGE**

In [ ]:
theory_marks=np.random.randint(0,100,size=50)
practical_marks=np.random.randint(0,51,size=50)
print("theory marks :",theory_marks)
print("practical marks :",practical_marks)

theory marks : [46  9 44  1 82 85 55 28  6 14 58 94 98 84 15 76 96 96 88 78 58 13 43 81
 27 35 86 80 46 95 54 30 86 35 12 81 27 87 86  2  4 57 67 19 80 47 26 47
 87 18]
practical marks : [26  3 22 11  7 41  2 17 40 48 38 16 13  4 44 38  5 31 49 14 24 41  0 18
 30 13 31  3 49  4 22  2 15 46 31  9  8  9 19 21 37 35  9 42 40 18 11 24
 35 32]


In [ ]:
theory_weightage=0.4
practical_weightage=0.6
final_scores=(theory_weightage*theory_marks)+(practical_weightage*practical_marks)
print("final score :",final_scores)

final score : [34.   5.4 30.8  7.  37.  58.6 23.2 21.4 26.4 34.4 46.  47.2 47.  36.
 32.4 53.2 41.4 57.  64.6 39.6 37.6 29.8 17.2 43.2 28.8 21.8 53.  33.8
 47.8 40.4 34.8 13.2 43.4 41.6 23.4 37.8 15.6 40.2 45.8 13.4 23.8 43.8
 32.2 32.8 56.  29.6 17.  33.2 55.8 26.4]
